remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme
title: Kubernetes für Einsteiger
description: Am Ende des Talks weist Du, wie du wie Du grundlegend mit Kubernetes umgehen kannst. Du kannst Deine Docker-Container in Kubernetes deployen und skalieren. Du kannst Kubernetes-Cluster aufsetzen und verwalten.
show_downloads: true
